### ISSUE TITLE
Availability on F-droid

### ISSUE THREAD

**Issue by marmeladema** [JiriSko/amixer-webui-android#1]
Hi !

Since your application is open source, i think it would be nice if it was available on F-droid.
What do you think about that ?

For further reading:
[https://f-droid.org/wiki/page/Inclusion_Policy](url)
[https://f-droid.org/wiki/page/Repository_Style_Guide](url)

Thank in advance !

**Comment by JiriSko** [comment]
Hi,

I like it. I'll consider it. :)

**Comment by julianhughes** [comment]
Just a +1 for submitting to f-droid.  I'm finding  amixer-webui and  amixer-webui-android a real boon, thank you.  If the Android app had been on f-droid I probably would have discovered amixer-webui much sooner.  I running amixer-webui on ARMv7 (armbian on Orange Pi One) and combined with the Android app on my ancient Galaxy Note II it gives me exactly what I need.  You saved me from the hideous curse of pulseaudio on embedded!  I have the convenience of remote control combined with the sound quality of direct hardware access without mixers.  Saint Cecilia is smiling on you :-)
